language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
env:
  - DB=mysql
  - DB=mysqli
  - DB=pgsql
  - DB=sqlite
  - DB=pdo/mysql
  - DB=pdo/pgsql
  - DB=pdo/sqlite

before_script:
  - composer install --dev --no-progress
  - sh -c "if [ '$DB' = 'pgsql' ] || [ '$DB' = 'pdo/pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS ci_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ] || [ '$DB' = 'pdo/pgsql' ]; then psql -c 'create database ci_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ] || [ '$DB' = 'mysqli' ] || [ '$DB' = 'pdo/mysql' ]; then mysql -e 'create database IF NOT EXISTS ci_test;'; fi"

script: phpunit -d zend.enable_gc=0 -d date.timezone=UTC --coverage-text --configuration tests/travis/$DB.phpunit.xml

matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: hhvm
      env: DB=pgsql
    - php: hhvm
      env: DB=pdo/pgsql

branches:
  only:
    - develop
    - /^feature\/.+$/