language: php
os: linux
dist: xenial

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  - DB=mysqli
  - DB=pgsql
  - DB=sqlite
  - DB=pdo/mysql
  - DB=pdo/pgsql
  - DB=pdo/sqlite

services:
  - mysql
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - sh -c "composer install --no-progress"
  - sh -c "if [ '$DB' = 'pgsql' ] || [ '$DB' = 'pdo/pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS ci_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ] || [ '$DB' = 'pdo/pgsql' ]; then psql -c 'create database ci_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ] || [ '$DB' = 'mysqli' ] || [ '$DB' = 'pdo/mysql' ]; then mysql -e 'create database IF NOT EXISTS ci_test;'; fi"

script: php -d zend.enable_gc=0 -d date.timezone=UTC -d mbstring.func_overload=7 -d mbstring.internal_encoding=UTF-8 vendor/bin/phpunit --coverage-text --configuration tests/travis/$DB.phpunit.xml

jobs:
  allow_failures:
    - php: nightly
    - php: hhvm-3.30
  include:
    - php: 5.4
      dist: trusty
      env: DB=mysql
    - php: 5.4
      dist: trusty
      env: DB=mysqli
    - php: 5.4
      dist: trusty
      env: DB=pgsql
    - php: 5.4
      dist: trusty
      env: DB=sqlite
    - php: 5.4
      dist: trusty
      env: DB=pdo/mysql
    - php: 5.4
      dist: trusty
      env: DB=pdo/pgsql
    - php: 5.4
      dist: trusty
      env: DB=pdo/sqlite
    - php: 5.5
      dist: trusty
      env: DB=mysql
    - php: 5.5
      dist: trusty
      env: DB=mysqli
    - php: 5.5
      dist: trusty
      env: DB=pgsql
    - php: 5.5
      dist: trusty
      env: DB=sqlite
    - php: 5.5
      dist: trusty
      env: DB=pdo/mysql
    - php: 5.5
      dist: trusty
      env: DB=pdo/pgsql
    - php: 5.5
      dist: trusty
      env: DB=pdo/sqlite
    - php: 5.6
      dist: xenial
      env: DB=mysql
    - php: hhvm-3.30
      dist: trusty
      env: DB=mysql
    - php: hhvm-3.30
      dist: trusty
      env: DB=mysqli
    - php: hhvm-3.30
      dist: trusty
      env: DB=sqlite
    - php: hhvm-3.30
      dist: trusty
      env: DB=pdo/mysql
    - php: hhvm-3.30
      dist: trusty
      env: DB=pdo/sqlite

branches:
  only:
    - develop
    - 3.0-stable
    - 3.1-stable
    - /^feature\/.+$/
